---
- hosts: srv1
  become: true
  tasks:
    - name: add php repository
      shell: sudo add-apt-repository ppa:ondrej/php -y

    - name: add postgresql repository
      shell: wget wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

    - name: add command
      shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/postgresql-pgdg.list > /dev/null

    - name: update
      apt:
        update_cache: yes

    - name: install postgresql
      apt: 
        name: ['postgresql-14'] 

    - name: install nginx&PHP
      apt:
        pkg:
        - nginx
        - php8.0-fpm
        - php8.0-pgsql
        - php8.0-common
        - composer
        - ca-certificates
        - apt-transport-https
        - software-properties-common

    - name: set timezone
      timezone:
        name: Asia/Jakarta       

    - name: Setup nginx
      template:
        src: onomi.j2
        dest: /etc/nginx/sites-available/onomi
        #shell: ln -s /etc/nginx/site-available/onomi /etc/nginx/site-enabled/  

    - name: clone Laravel repository 
      git:
        repo: https://github.com/laravel/laravel.git
        dest: /var/www/laravel
        update: yes
      register: cloned

    - name: setup Laravel
      shell: |
          mv laravel onomi
          cd onomi
          sudo: yes
          sudo_user: www:data        
