---
- hosts: srv1
  become: true
  tasks:
    - name : add repo
      shell: sudo add-apt-repository ppa:ondrej/php -y
    - name: update
      apt:
        update_cache: yes  
    - name: install nginx&PHP
      apt:
        pkg:
        - nginx
        - php8.0-fpm
        - php8.0-common

    - name: nginx host  
      template:
        src : site.j2
        dest: /etc/nginx/sites-enabled/site
      notify: restart nginx

    - name: create web-root directory
      file:
        path: /var/www/site/index.php
        state: directory

    - name: upload index.html
      template:
        src: index.php.j2
        dest: /var/www/site/index.php    

- hosts: srv2
  become: true
  tasks:
    - name: update&addsources
      shell: wget wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    - name: add command
      shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/postgresql-pgdg.list > /dev/null  
    - name: update
      apt:
        update_cache: yes  
    - name: install postgresql
      apt: 
        name: ['postgresql-14']